export const MAX_BOARD_TITLE_LENGTH = 128;
export const MAX_LIST_TITLE_LENGTH = 128;
export const MAX_CARD_TITLE_LENGTH = 512;
export const MAX_DESCRIPTION_LENGTH = 1024;
export const MAX_LABEL_TITLE_LENGTH = 40;
export const MAX_CHECKLIST_TITLE_LENGTH = 128;
export const MAX_CHECKLIST_ITEM_LENGTH = 512;
